### ISSUE TITLE
感謝

### ISSUE THREAD

**Issue by sorat0mo** [duckfly-tw/fcitx5-extra-tables-deb#1]
這個不是Issue，單純想留言，在Ubuntu苦尋fcitx5-table-extra的package很久都沒有結果，終於有人幫忙打包成安裝檔了…雖然沒有ppa但還是很感謝你。我本來想捐款但好像沒有開捐款

**Comment by duckfly-tw** [comment]
當初是為了幫忙同事解決輸入法的問題才做了這個打包，也很高興能幫助到您。
